[tox]
envlist =
    py{313},
    coverage

[gh-actions]
python =
    3.13: py313

[testenv]
usedevelop = true
setenv =
    COVERAGE_FILE={toxinidir}/.coverage_{envname}
deps =
    pdbpp==0.11.6
    pytest==8.3.5
    pytest-cov==6.1.1
commands =
    pytest --cov-report= --cov=obd {posargs}

[testenv:coverage]
skipsdist = true
deps =
    coverage
whitelist_externals =
    /bin/bash
commands =
    /bin/bash -c 'coverage combine {toxinidir}/.coverage_*'
    coverage html -i
    coverage report -i --show-missing

[flake8]
max-line-length = 120

[coverage:run]
omit =
    .tox/*
    env/*
    .env

[coverage:paths]
source =
    obd/
